services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: papermap_db
      POSTGRES_USER: ${VITE_DB_USER}
      POSTGRES_PASSWORD: ${VITE_DB_PASSWORD}
    volumes:
      - ./data/journals.csv:/docker-entrypoint-initdb.d/journals.csv:ro
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "127.0.0.1:${VITE_DB_PORT}:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "80:3000"
    restart: always
