services:
  app:
    build: .
    ports:
      - "80:3000"
    restart: always
    env_file:
      - .env
    environment:
      NODE_OPTIONS: "--experimental-loader=newrelic/esm-loader.mjs -r newrelic"
