name: CI

on:
  pull_request:
    branches: [main]

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max_old_space_size=4096

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy the project
        run: npm run deploy

      - name: Ping the server
        run: ping -c 4 localhost

      - name: Clean up
        run: docker compose down
