name: CI

on:
  pull_request:
    branches: [main]

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Validate Docker configuration
        run: docker compose config

      - name: Build the project
        run: npm run build

      - name: Deploy the project
        run: npm run deploy

      - name: Ping the server
        run: ping -c 4 localhost

      - name: Clean up
        run: docker compose down
