name: Issue

on:
  issues:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd ~/Papermap
          npm i discord.js
          npm run discord -- \
            "issue" \
            "${{ github.event.issue.html_url }}" \
            "${{ replace(github.event.issue.title, '"', '\\"') }}" \
            "${{ replace(replace(github.event.issue.body, '"', '\\"'), '\n', '\\n') }}" \
            "${{ github.event.issue.user.login }}" \
            "${{ join(github.event.issue.labels.*.name, ',') }}"
