name: Discord

on:
  issues:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd ~/Papermap
          npm run discord -- \
            "issue"
            "${{ github.event.issue.html_url }}"
            "${{ github.event.issue.title }}"
            "${{ github.event.issue.body }}"
            "${{ github.event.issue.user.login }}"
            "${{ join(github.event.issue.labels.*.name, ',') }}"
