name: Issue

on:
  issues:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      env:
        URL: ${{ github.event.issue.html_url }}
        TITLE: ${{ github.event.issue.title }}
        BODY: ${{ github.event.issue.body }}
        USER: ${{ github.event.issue.user.login }}
        LABELS: ${{ join(github.event.issue.labels.*.name, ',') }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        envs: URL,TITLE,BODY,USER,LABELS
        script: |
          cd ~/Papermap
          npm i discord.js
          echo "$TITLE"
          npm run discord -- "issue" "$URL" "$TITLE" "$BODY" "$USER" "$LABELS"
