name: PR

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  discord-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Send PR to Discord
      env:
        URL: ${{ github.event.pull_request.html_url }}
        TITLE: ${{ github.event.pull_request.title }}
        BODY: ${{ github.event.pull_request.body }}
        USER: ${{ github.event.pull_request.user.login }}
        LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        envs: URL,TITLE,BODY,USER,LABELS
        script: |
          cd ~/Papermap
          npm i discord.js
          echo "$TITLE"
          npm run discord -- "pull request" "$URL" "$TITLE" "$BODY" "$USER" "$LABELS"
